version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_ADDR=db_keycloak
      - DB_DATABASE=keycloak
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "8081:8080"
    depends_on:
      - db_keycloak

  db_keycloak:
    image: postgres:15
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  db_main:
    image: postgres:15
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DB_PORT=5450
    volumes:
      - postgres_data_main:/var/lib/postgresql/data
    ports:
      - "5451:5432"

volumes:
  postgres_data_keycloak:
  postgres_data_main:
